# Generated by Django 4.1.8 on 2024-03-22 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficViolation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=utils.models.make_uuid,
                        help_text="Id",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="描述",
                        max_length=100,
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        help_text="修改人",
                        max_length=100,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "dept_belong_id",
                    models.CharField(
                        blank=True,
                        help_text="数据归属部门",
                        max_length=100,
                        null=True,
                        verbose_name="数据归属部门",
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                ("car_number", models.CharField(max_length=20, verbose_name="车牌号")),
                (
                    "violation_type",
                    models.CharField(max_length=100, verbose_name="违规内容"),
                ),
                ("violation_time", models.DateTimeField(verbose_name="违规时间")),
                (
                    "has_paid",
                    models.BooleanField(default=False, verbose_name="是否已缴纳罚款"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "交通违章信息",
                "verbose_name_plural": "交通违章信息",
                "db_table": "tb_traffic_violation",
            },
        ),
    ]
